name: Step 0, Welcome

# This step triggers after the learner creates a new repository from the template.
# This workflow updates from step 0 to step 1.

# This will run every time we create push a commit to `main`.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  step_validate_and_update:
    uses: ./.github/workflows/reusable-step-validate-and-update.yml
    secrets: inherit
    with:
      expected_step: "0"
      from_step: "0"
      to_step: "1"
      fetch_depth: 0
