name: Step 1, Copilot Extension in a Codespace

# This step triggers after push to main#devcontainer.json.
# This workflow updates from step 1 to step 2.

# This will run every time we main#devcontainer.json
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    paths:
      - ".devcontainer/devcontainer.json"
    branches:
      - main

jobs:
  step_validate_and_update:
    uses: ./.github/workflows/reusable-step-validate-and-update.yml
    secrets: inherit
    with:
      expected_step: "1"
      from_step: "1"
      to_step: "2"
      check_file: ".devcontainer/devcontainer.json"
      check_search: "GitHub\\.copilot"
