name: Step 2, Javascript function

# This step triggers after push to main#skills.js.
# This workflow updates from step 2 to step 3.

# This will run every time we push to main#skills.js.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    paths:
      - "skills.js"
    branches:
      - main

jobs:
  step_validate_and_update:
    uses: ./.github/workflows/reusable-step-validate-and-update.yml
    secrets: inherit
    with:
      expected_step: "2"
      from_step: "2"
      to_step: "3"
      check_file: "skills.js"
      check_search: "function calculateNumbers"
      fetch_depth: 0
