name: Step 3, Copilot hub suggestion

# This step triggers after push to main#member.js.
# This workflow updates from step 3 to step 4.

# This will run every time we push to main#member.js.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    paths:
      - "member.js"
    branches:
      - main

jobs:
  step_validate_and_update:
    uses: ./.github/workflows/reusable-step-validate-and-update.yml
    secrets: inherit
    with:
      expected_step: "3"
      from_step: "3"
      to_step: "4"
      check_file: "member.js"
      check_search: "skillsMember"
      fetch_depth: 0
